### ISSUE TITLE
may you share MIMIC III data and trained wordtovec

### ISSUE THREAD

**Issue by Sandy4321** [SmokeShine/Convolutional-Attention-forMultiLabel-classification-CAML#1]
great code may you share MIMIC III data and trained wordtovec  pls
per
https://www.youtube.com/watch?v=F-pA0zNAn64&t=98s
98 sec
<img width="1142" alt="image" src="https://github.com/SmokeShine/Convolutional-Attention-forMultiLabel-classification-CAML/assets/11426119/5388c821-fe8c-4b14-bf56-43f19b4fe664">

**Comment by SmokeShine** [comment]
You can access the data by raising a request from this page.

https://physionet.org/content/mimiciii/1.4/

**Comment by Sandy4321** [comment]
IT IS IMPOSSBLE PROCESS IS SO COMPLICTED.. 
THEY ARE SO GREADY ...
